### ISSUE TITLE
RFC Champs

### ISSUE THREAD

**Issue by tchak** [demarche-numerique/demarche.numerique.gouv.fr#10102]
## Objectifs fonctionnels

- Plus de dossiers coincés sur de vieilles révisions.
- La possibilité pour les instructeurs de faire des changements sur le dossier.
- Garder l'historique des modifications sur les dossiers déposés.
- Moins de bugs lors des rebases et des merges de forks.
- Avoir accès aux informations saisies sur les révisions précédentes (ne plus supprimer de données).

## Objectifs techniques

- Supprimer le rebase (source de bugs, opération lourde, suppression de données).
- Simplifier le fork/merge.
- Alléger la base : ne plus créer les champs vides.

## Étapes nécessaires

- [ ] Rendu du dossier avec des champs manquants (#10108)
- [ ] Ajouter le `stable_id` sur les champs et supprimer le `type_de_champ_id` (#10109)
- [ ] Implémenter la projection des valeurs des champs en fonction du type de champ de la révision (#10108)
- [ ] Écrire dans les champs via un upsert.
- [ ] Matérialiser les lignes des répétitions afin de pouvoir insérer une ligne sans insérer tous ses champs.
- [ ] Ajouter les namespaces et migrer les champs des fork dans le namespace "draft:user" (#10109)

## L'algorithme de fork/merge

Seule modification du model de données : on ajoute les colonnes `stable_id`, `namespace` et `updated_by` sur la table `champs`. On supprime la colonne `type_de_champ_id`
On ajoute un index unique sur `[dossier_id, namespace, stable_id, row_id]`

Un `namespace` peut avoir trois valeur fixes `main` (default), `draft:user` et `draft:instructeur` ou alors un timestamp de merge (ex: `history:2024-02-08T00:00:00.000Z`)

Une modification de la valeur d'un champ est toujours un upsert sur l'index `[dossier_id, namespace, stable_id, row_id]`. Si le dossier est en "brouillon", le `namespace` est toujours `main`. Si le dossier est "en construction", les utilisateurs écrivent dans le namespace `draft:user` et les instructeurs dans le namespace `draft:instructeur`. Il est à noter que sur ces trois namespaces, seule la dernière valeur est conservée, écrasant ainsi le `updated_at` et le `updated_by`.

Pour lire la version en cours on prend tout les champs sur "main" `Champ.where(dossier_id:, namespace: 'main')`. Pour lire un des draft on sélectionne le bon namespace de draft + le "main" `Champ.where(dossier_id:, namespace: ['main', 'draft:user']).order(:updated_at)` et on prend pour chaque `stable_id` la dernière valeur. Vous noterez qu'en théorie, il est possible d'afficher la valeur du "main" en cours.

Le merge par un utilisateur se fait à l'aide de deux `update_all`. Comme nous l'avons discuté précédemment, les changements de l'utilisateur écrasent d'éventuels changements de l'instructeur qui ont été faits après que l'utilisateur ait mergé des modifications sur le "main".

```ruby
draft_champs = dossier.champs.where(namespace: 'draft:user')
  .pluck(:id, :stable_id, :row_id)
  .index_by { |(_, stable_id, row_id)| [stable_id, row_id].compact }
  .transform_values(&:first)

main_champs = dossier.champs.where(namespace: 'main')
  .pluck(:id, :stable_id, :row_id)
  .index_by { |(_, stable_id, row_id)| [stable_id, row_id].compact }
  .transform_values(&:first)

draft_champ_ids = draft_champs.values
main_champ_ids = main_champs.filter_map do |key, id|
  id if draft_champs.key?(key)
end

now = Time.zone.now
dossier.tranasaction do
  dossier.champs.where(id: main_champ_ids, namespace: 'main').update_all(namespace: "history:#{now}")
  dossier.champs.where(id: draft_champ_ids, namespace: "draft:user").update_all(namespace: "main", updated_at: now)
end
```
On déplace les champs modifié vers un namespace d'historique et on promeut les champs en "draft" vers le "main" en modifiant leur `updated_at` pour qu'il corresponde à la date de merge.

Le merge par un instructeur comporte une étape supplémentaire de rejet des changements effectués après les modifications sur "main" :
```ruby
draft_champs = dossier.champs.where(namespace: 'draft:instructeur')
  .pluck(:id, :stable_id, :row_id, :updated_at)
  .map do |(id, stable_id, row_id, updated_at)|
    [[stable_id, row_id].compact, [id, updated_at]]
  end.to_h

main_champs = dossier.champs.where(namespace: 'main')
  .pluck(:id, :stable_id, :row_id, :updated_at)
  .map do |(id, stable_id, row_id, updated_at)|
    [[stable_id, row_id].compact, [id, updated_at]]
  end.to_h

updated_draft_champ_ids, rejected_draft_champ_ids = draft_champs.partition do |key, (_, updated_at)|
  main_champs.key?(key) ? updated_at > main_champs[key].last : true
end.map(&:last).map(&:first)

main_champ_ids = main_champs.filter_map do |key, (id, _)|
  id if draft_champs.key?(key)
end

now = Time.zone.now
dossier.tranasaction do
  dossier.champs.where(id: updated_draft_champ_ids, namespace: 'main').update_all(namespace: "history:#{now}")
  dossier.champs.where(id: updated_draft_champ_ids, namespace: 'draft:instructeur').update_all(namespace: "main", updated_at: now)
  dossier.champs.where(id: rejected_draft_champ_ids, namespace: 'draft:instructeur').destroy_all
end
```

Si on veut récupérer les valeurs d'un dossier à une date précise, il suffit de faire :
```ruby
Champ.where(dossier_id:, updated_at:..date).not(namespace: ["draft:user", "draft:instructeur"])
```
