### ISSUE TITLE
Les traductions manquantes pour une bonne expérience de nouveaux arrivants sur la plateforme

### ISSUE THREAD

**Issue by tchak** [demarche-numerique/demarche.numerique.gouv.fr#6421]
- [x] Les mails indiquant que le dossier est réexaminé (#6422)
- [x] Le mail informatif de création d’un brouillon est en français (pour les autres mails attachés à la demande, il me semble que nous avons la main sur le template côté MEAE) (#6420)
- [x] Le mail de validation de création de compte est en français (#6420)
- [x] Le mail de réinitialisation du mot de passe est en français (#6420)
- [x] Les boutons « Consulter mon dossier » et « j’ai une question » des mails de notification sont en français. (#6422)
- [x] La page [https://www.demarches-simplifiees.fr/users/confirmation/new?user%5Bemail%5D=xxxxxx](https://www.demarches-simplifiees.fr/users/confirmation/new?user%5Bemail%5D=xxxxxx) est en français (#6438)
- [x] La page [https://www.demarches-simplifiees.fr/users/password/new](https://www.demarches-simplifiees.fr/users/password/new) : « Demander un nouveau mot de passe » n’est pas traduit (#6424)
- [x] ~Bouton « parcourir » en français~ this is about file picker button – it is part of browser UI and will be in the language of the browser/system.
